import type { LessonSpec } from "./lesson-spec";

export const sampleLessons: LessonSpec[] = [
  {
    version: "1.0",
    lessonId: "sarajevo-1914",
    title: "Sarajevo, 1914",
    subject: "History",
    gradeLevel: 7,
    template: "cinematic_timeline",
    status: "review",
    summary: "Trace the decisions and alliances that turned one morning in Sarajevo into a continental war.",
    createdAt: "2026-07-10T14:32:00.000Z",
    phases: [
      {
        phaseId: "sarajevo-1",
        beatTitle: "A city under watch",
        learningObjective: "Locate Sarajevo and identify why the royal visit carried political tension.",
        narration: "On June 28, 1914, Archduke Franz Ferdinand arrived in Sarajevo, a city shaped by competing national identities and imperial rule.",
        durationMinutes: 4,
        scene: { environment: "sunlit_sarajevo_street", cameraMove: "crane_down_to_street", accent: "#c4614f", assetQueries: ["european street", "vintage car", "newspaper stand"] },
        interaction: { type: "objective", prompt: "Find the newspaper stand and inspect the published route.", completionEvent: "inspect_newspaper" },
        claims: [
          { id: "claim-1", claim: "Franz Ferdinand visited Sarajevo on June 28, 1914.", source: "https://www.britannica.com/event/assassination-of-Franz-Ferdinand-Archduke-of-Austria", sourceTitle: "Encyclopaedia Britannica", confidence: "high", teacherApproved: true },
        ],
        teacherNote: "Ask students why publishing an itinerary might create risk.",
      },
      {
        phaseId: "sarajevo-2",
        beatTitle: "The route changes",
        learningObjective: "Explain how a navigation mistake created an unexpected encounter.",
        narration: "After an earlier attack failed, the motorcade changed plans. A wrong turn brought the car to a stop near Gavrilo Princip.",
        durationMinutes: 5,
        scene: { environment: "riverside_motorcade", cameraMove: "follow_actor", accent: "#9a6756", assetQueries: ["vintage open car", "city crowd", "stone bridge"] },
        interaction: { type: "explore", prompt: "Follow the route markers and identify the turning point.", completionEvent: "route_complete" },
        claims: [
          { id: "claim-2", claim: "The driver took a wrong turn and stopped near Gavrilo Princip.", source: "https://encyclopedia.1914-1918-online.net/article/sarajevo_assassination/", sourceTitle: "1914-1918 Online", confidence: "high", teacherApproved: false },
        ],
        teacherNote: "Separate contingency from inevitability. The event depended on several failed and accidental moments.",
      },
      {
        phaseId: "sarajevo-3",
        beatTitle: "A protected viewpoint",
        learningObjective: "Describe the event without placing students in a violent role.",
        narration: "The scene cuts away as the assassination occurs. Students return as observers to examine how leaders responded afterward.",
        durationMinutes: 3,
        scene: { environment: "cinematic_cutaway", cameraMove: "cutaway", accent: "#765f58", assetQueries: ["historic city skyline", "newspaper"] },
        interaction: { type: "quiz", prompt: "Which detail best shows that the assassination was not inevitable?", completionEvent: "quiz_complete", choices: ["The date was fixed", "Several earlier attempts failed", "The city had a river", "The visit was public"], answerIndex: 1 },
        claims: [],
        teacherNote: "Keep focus on causation and response, not graphic detail.",
      },
      {
        phaseId: "sarajevo-4",
        beatTitle: "From crisis to war",
        learningObjective: "Connect alliance obligations and political choices to the widening conflict.",
        narration: "Austria-Hungary's ultimatum to Serbia triggered a chain of mobilizations. Alliances expanded a regional crisis into a European war.",
        durationMinutes: 6,
        scene: { environment: "animated_alliance_map", cameraMove: "slow_motion_orbit", accent: "#456a65", assetQueries: ["europe map", "paper document", "telegraph"] },
        interaction: { type: "objective", prompt: "Connect each country to the alliance that shaped its decision.", completionEvent: "alliances_mapped" },
        claims: [
          { id: "claim-3", claim: "Austria-Hungary issued an ultimatum to Serbia in July 1914.", source: "https://encyclopedia.1914-1918-online.net/article/july_crisis_1914/", sourceTitle: "1914-1918 Online", confidence: "high", teacherApproved: true },
        ],
        teacherNote: "The headline takeaway is that alliances created pressure, but leaders still made choices.",
      },
    ],
    safetyReport: {
      flags: [
        { id: "safety-1", phaseId: "sarajevo-3", issue: "Historical violence was initially framed as a playable student action.", adjustment: "Student role changed to protected observer. The event is handled through a cinematic cutaway and the task shifts to evaluating consequences.", severity: "adjusted", teacherApproved: false },
      ],
    },
  },
  {
    version: "1.0",
    lessonId: "cell-journey",
    title: "Journey Through a Cell",
    subject: "Biology",
    gradeLevel: 6,
    template: "scale_journey",
    status: "published",
    classCode: "CELL42",
    summary: "Shrink to microscopic scale and meet the structures that keep a cell alive.",
    createdAt: "2026-07-08T09:12:00.000Z",
    phases: [
      {
        phaseId: "cell-1",
        beatTitle: "Crossing the membrane",
        learningObjective: "Explain how the cell membrane controls movement into and out of a cell.",
        narration: "The membrane is a selective boundary. It lets some materials pass while keeping the cell's internal conditions stable.",
        durationMinutes: 4,
        scene: { environment: "cell_membrane", cameraMove: "scale_dive", accent: "#4c7b70", assetQueries: ["cell membrane", "phospholipid"] },
        interaction: { type: "objective", prompt: "Sort three molecules by whether they can cross the membrane.", completionEvent: "membrane_sorted" },
        claims: [],
        teacherNote: "Use the school-door analogy, then name where the analogy breaks down.",
      },
      {
        phaseId: "cell-2",
        beatTitle: "Power at the mitochondrion",
        learningObjective: "Relate mitochondria to the release of usable energy from food.",
        narration: "Mitochondria transform energy stored in food into ATP, a form the cell can use for its work.",
        durationMinutes: 5,
        scene: { environment: "mitochondria_field", cameraMove: "orbit_subject", accent: "#b65e4d", assetQueries: ["mitochondria", "ATP molecule"] },
        interaction: { type: "dialogue", prompt: "Ask the mitochondrion what it needs and what it produces.", completionEvent: "npc_conversation" },
        claims: [],
        teacherNote: "Listen for students saying mitochondria create energy. Clarify that they transform it.",
      },
      {
        phaseId: "cell-3",
        beatTitle: "Inside the nucleus",
        learningObjective: "Describe DNA as stored instructions used by the cell.",
        narration: "The nucleus protects most of the cell's DNA. Different parts of those instructions are used when the cell needs particular proteins.",
        durationMinutes: 5,
        scene: { environment: "nucleus_interior", cameraMove: "scale_dive", accent: "#6b6e91", assetQueries: ["cell nucleus", "DNA helix"] },
        interaction: { type: "quiz", prompt: "What is the best description of DNA in this lesson?", completionEvent: "quiz_complete", choices: ["Stored instructions", "Cell fuel", "A waste product", "The outer boundary"], answerIndex: 0 },
        claims: [],
        teacherNote: "Connect DNA instructions to the proteins students encounter next.",
      },
    ],
    safetyReport: { flags: [] },
  },
  {
    version: "1.0",
    lessonId: "limit-drop",
    title: "Limit Drop",
    subject: "Algebra",
    gradeLevel: 9,
    template: "parameter_sandbox",
    status: "published",
    classCode: "LIMIT9",
    gamePath: "/games/limit-drop",
    sourceType: "imported_game",
    summary: "Draw functions as physical rails, predict an egg's path, and revise until it lands safely in the basket.",
    createdAt: "2026-07-12T10:42:00.000Z",
    phases: [
      {
        phaseId: "limit-drop-1",
        beatTitle: "Read the farm coordinate plane",
        learningObjective: "Connect horizontal and vertical position in the game world to x and f(x).",
        narration: "The farm is a coordinate plane. Every function you type becomes a rail whose height is f of x.",
        durationMinutes: 4,
        scene: { environment: "moonlit_function_farm", cameraMove: "sandbox_wide", accent: "#7daee8", assetQueries: ["low poly night farm", "wooden basket", "chicken", "farm fence"] },
        interaction: { type: "sandbox_params", prompt: "Enter a decreasing linear function and inspect the rail before dropping the egg.", completionEvent: "first_valid_function" },
        claims: [{ id: "limit-claim-1", claim: "The graph of a linear function has a constant rate of change.", source: "https://openstax.org/books/elementary-algebra-2e/pages/4-2-graph-linear-equations-in-two-variables", sourceTitle: "OpenStax Elementary Algebra", confidence: "high", teacherApproved: true }],
        teacherNote: "Ask students what the coefficient of x changes physically: the steepness and direction of the rail.",
      },
      {
        phaseId: "limit-drop-2",
        beatTitle: "First Flight",
        learningObjective: "Use slope and intercept to guide an object from a known starting point to a target.",
        narration: "A gently decreasing line can carry the egg from the hen to the basket. Students predict, drop, observe, and revise.",
        durationMinutes: 6,
        scene: { environment: "open_farm_field", cameraMove: "sandbox_wide", accent: "#00bda5", assetQueries: ["farm field", "hen", "egg", "basket"] },
        interaction: { type: "sandbox_params", prompt: "Build a linear rail from the hen at negative x to the basket at positive x.", completionEvent: "level_1_caught" },
        claims: [],
        teacherNote: "Do not give the equation immediately. Have students estimate the sign and magnitude of slope first.",
      },
      {
        phaseId: "limit-drop-3",
        beatTitle: "Over the Fence",
        learningObjective: "Use a downward-opening quadratic to maintain height over an obstacle and descend toward a target.",
        narration: "A straight path collides with the fence. A quadratic arch creates clearance while preserving a downward route to the basket.",
        durationMinutes: 8,
        scene: { environment: "fenced_farm_lane", cameraMove: "sandbox_wide", accent: "#f19a38", assetQueries: ["farm fence", "night field", "wood basket"] },
        interaction: { type: "sandbox_params", prompt: "Tune a quadratic function so the egg clears a fence at x equals zero.", completionEvent: "level_2_caught" },
        claims: [{ id: "limit-claim-2", claim: "A quadratic function can be represented by a parabola.", source: "https://openstax.org/books/intermediate-algebra-2e/pages/9-6-graph-quadratic-functions-using-properties", sourceTitle: "OpenStax Intermediate Algebra", confidence: "high", teacherApproved: true }],
        teacherNote: "Pause before each drop. Ask whether the vertex is high enough and whether the egg will still descend on the correct side.",
      },
      {
        phaseId: "limit-drop-4",
        beatTitle: "Mind the Hay",
        learningObjective: "Reason about function values over an interval and use a restricted domain to create a launch point.",
        narration: "Students can keep the rail above both hay bales or end its domain early and let momentum carry the egg through the air.",
        durationMinutes: 8,
        scene: { environment: "hay_bale_course", cameraMove: "follow_actor", accent: "#f4c454", assetQueries: ["hay bale", "farm obstacle course", "egg basket"] },
        interaction: { type: "sandbox_params", prompt: "Clear both hay bales using function height, domain limits, or both.", completionEvent: "level_3_caught" },
        claims: [],
        teacherNote: "Connect the from/to controls to domain notation. The graph only exists on the interval students choose.",
      },
      {
        phaseId: "limit-drop-5",
        beatTitle: "High Delivery",
        learningObjective: "Target a specific output value rather than assuming the destination lies on the x-axis.",
        narration: "The basket is elevated. Students must make the rail arrive near a required y-value instead of returning to the ground.",
        durationMinutes: 7,
        scene: { environment: "raised_basket_farm", cameraMove: "orbit_subject", accent: "#e783ae", assetQueries: ["wood crate", "raised basket", "night farm"] },
        interaction: { type: "sandbox_params", prompt: "Make the egg reach a basket at approximately x equals six and y equals three point five.", completionEvent: "level_4_caught" },
        claims: [],
        teacherNote: "Ask students to evaluate their function at x equals six before testing.",
      },
      {
        phaseId: "limit-drop-6",
        beatTitle: "The Piecewise Gauntlet",
        learningObjective: "Construct and revise a piecewise model with domain restrictions that solves a multi-stage physical constraint.",
        narration: "The final route combines a launch curve with a second rail behind the barn. No single familiar form solves every constraint cleanly.",
        durationMinutes: 12,
        scene: { environment: "barn_gauntlet", cameraMove: "sandbox_wide", accent: "#9b8bf4", assetQueries: ["red barn", "farm fence", "windmill", "basket"] },
        interaction: { type: "sandbox_params", prompt: "Use two domain-restricted functions to clear the fence and barn, then redirect the egg into the basket.", completionEvent: "boss_level_caught" },
        claims: [{ id: "limit-claim-3", claim: "A piecewise-defined function uses different formulas on different parts of its domain.", source: "https://openstax.org/books/college-algebra-2e/pages/1-2-domain-and-range", sourceTitle: "OpenStax College Algebra", confidence: "high", teacherApproved: true }],
        teacherNote: "Have pairs explain why each piece exists, where its domain begins and ends, and what physical job it performs.",
      },
    ],
    safetyReport: { flags: [] },
  },
];

export const limitDropLesson = sampleLessons.find((lesson) => lesson.lessonId === "limit-drop")!;

export const getLesson = (id: string) => sampleLessons.find((lesson) => lesson.lessonId === id) ?? sampleLessons[0];
