import type { LessonSpec } from "./lesson-spec";

export const sampleLessons: LessonSpec[] = [
  {
    version: "1.0",
    lessonId: "sarajevo-1914",
    title: "Sarajevo, 1914",
    subject: "History",
    gradeLevel: 7,
    template: "cinematic_timeline",
    status: "review",
    summary: "Trace the decisions and alliances that turned one morning in Sarajevo into a continental war.",
    createdAt: "2026-07-10T14:32:00.000Z",
    phases: [
      {
        phaseId: "sarajevo-1",
        beatTitle: "A city under watch",
        learningObjective: "Locate Sarajevo and identify why the royal visit carried political tension.",
        narration: "On June 28, 1914, Archduke Franz Ferdinand arrived in Sarajevo, a city shaped by competing national identities and imperial rule.",
        durationMinutes: 4,
        scene: { environment: "sunlit_sarajevo_street", cameraMove: "crane_down_to_street", accent: "#c4614f", assetQueries: ["european street", "vintage car", "newspaper stand"] },
        interaction: { type: "objective", prompt: "Find the newspaper stand and inspect the published route.", completionEvent: "inspect_newspaper" },
        claims: [
          { id: "claim-1", claim: "Franz Ferdinand visited Sarajevo on June 28, 1914.", source: "https://www.britannica.com/event/assassination-of-Franz-Ferdinand-Archduke-of-Austria", sourceTitle: "Encyclopaedia Britannica", confidence: "high", teacherApproved: true },
        ],
        teacherNote: "Ask students why publishing an itinerary might create risk.",
      },
      {
        phaseId: "sarajevo-2",
        beatTitle: "The route changes",
        learningObjective: "Explain how a navigation mistake created an unexpected encounter.",
        narration: "After an earlier attack failed, the motorcade changed plans. A wrong turn brought the car to a stop near Gavrilo Princip.",
        durationMinutes: 5,
        scene: { environment: "riverside_motorcade", cameraMove: "follow_actor", accent: "#9a6756", assetQueries: ["vintage open car", "city crowd", "stone bridge"] },
        interaction: { type: "explore", prompt: "Follow the route markers and identify the turning point.", completionEvent: "route_complete" },
        claims: [
          { id: "claim-2", claim: "The driver took a wrong turn and stopped near Gavrilo Princip.", source: "https://encyclopedia.1914-1918-online.net/article/sarajevo_assassination/", sourceTitle: "1914-1918 Online", confidence: "high", teacherApproved: false },
        ],
        teacherNote: "Separate contingency from inevitability. The event depended on several failed and accidental moments.",
      },
      {
        phaseId: "sarajevo-3",
        beatTitle: "A protected viewpoint",
        learningObjective: "Describe the event without placing students in a violent role.",
        narration: "The scene cuts away as the assassination occurs. Students return as observers to examine how leaders responded afterward.",
        durationMinutes: 3,
        scene: { environment: "cinematic_cutaway", cameraMove: "cutaway", accent: "#765f58", assetQueries: ["historic city skyline", "newspaper"] },
        interaction: { type: "quiz", prompt: "Which detail best shows that the assassination was not inevitable?", completionEvent: "quiz_complete", choices: ["The date was fixed", "Several earlier attempts failed", "The city had a river", "The visit was public"], answerIndex: 1 },
        claims: [],
        teacherNote: "Keep focus on causation and response, not graphic detail.",
      },
      {
        phaseId: "sarajevo-4",
        beatTitle: "From crisis to war",
        learningObjective: "Connect alliance obligations and political choices to the widening conflict.",
        narration: "Austria-Hungary's ultimatum to Serbia triggered a chain of mobilizations. Alliances expanded a regional crisis into a European war.",
        durationMinutes: 6,
        scene: { environment: "animated_alliance_map", cameraMove: "slow_motion_orbit", accent: "#456a65", assetQueries: ["europe map", "paper document", "telegraph"] },
        interaction: { type: "objective", prompt: "Connect each country to the alliance that shaped its decision.", completionEvent: "alliances_mapped" },
        claims: [
          { id: "claim-3", claim: "Austria-Hungary issued an ultimatum to Serbia in July 1914.", source: "https://encyclopedia.1914-1918-online.net/article/july_crisis_1914/", sourceTitle: "1914-1918 Online", confidence: "high", teacherApproved: true },
        ],
        teacherNote: "The headline takeaway is that alliances created pressure, but leaders still made choices.",
      },
    ],
    safetyReport: {
      flags: [
        { id: "safety-1", phaseId: "sarajevo-3", issue: "Historical violence was initially framed as a playable student action.", adjustment: "Student role changed to protected observer. The event is handled through a cinematic cutaway and the task shifts to evaluating consequences.", severity: "adjusted", teacherApproved: false },
      ],
    },
  },
  {
    version: "1.0",
    lessonId: "cell-journey",
    title: "Journey Through a Cell",
    subject: "Biology",
    gradeLevel: 6,
    template: "scale_journey",
    status: "published",
    classCode: "CELL42",
    summary: "Shrink to microscopic scale and meet the structures that keep a cell alive.",
    createdAt: "2026-07-08T09:12:00.000Z",
    phases: [
      {
        phaseId: "cell-1",
        beatTitle: "Crossing the membrane",
        learningObjective: "Explain how the cell membrane controls movement into and out of a cell.",
        narration: "The membrane is a selective boundary. It lets some materials pass while keeping the cell's internal conditions stable.",
        durationMinutes: 4,
        scene: { environment: "cell_membrane", cameraMove: "scale_dive", accent: "#4c7b70", assetQueries: ["cell membrane", "phospholipid"] },
        interaction: { type: "objective", prompt: "Sort three molecules by whether they can cross the membrane.", completionEvent: "membrane_sorted" },
        claims: [],
        teacherNote: "Use the school-door analogy, then name where the analogy breaks down.",
      },
      {
        phaseId: "cell-2",
        beatTitle: "Power at the mitochondrion",
        learningObjective: "Relate mitochondria to the release of usable energy from food.",
        narration: "Mitochondria transform energy stored in food into ATP, a form the cell can use for its work.",
        durationMinutes: 5,
        scene: { environment: "mitochondria_field", cameraMove: "orbit_subject", accent: "#b65e4d", assetQueries: ["mitochondria", "ATP molecule"] },
        interaction: { type: "dialogue", prompt: "Ask the mitochondrion what it needs and what it produces.", completionEvent: "npc_conversation" },
        claims: [],
        teacherNote: "Listen for students saying mitochondria create energy. Clarify that they transform it.",
      },
      {
        phaseId: "cell-3",
        beatTitle: "Inside the nucleus",
        learningObjective: "Describe DNA as stored instructions used by the cell.",
        narration: "The nucleus protects most of the cell's DNA. Different parts of those instructions are used when the cell needs particular proteins.",
        durationMinutes: 5,
        scene: { environment: "nucleus_interior", cameraMove: "scale_dive", accent: "#6b6e91", assetQueries: ["cell nucleus", "DNA helix"] },
        interaction: { type: "quiz", prompt: "What is the best description of DNA in this lesson?", completionEvent: "quiz_complete", choices: ["Stored instructions", "Cell fuel", "A waste product", "The outer boundary"], answerIndex: 0 },
        claims: [],
        teacherNote: "Connect DNA instructions to the proteins students encounter next.",
      },
    ],
    safetyReport: { flags: [] },
  },
];

export const getLesson = (id: string) => sampleLessons.find((lesson) => lesson.lessonId === id) ?? sampleLessons[0];
