'use client';

import dynamic from 'next/dynamic';
import { useState } from 'react';
import { ChevronRight, File, Folder } from 'lucide-react';
import { TEMPLATE_CODE } from '@/lib/fixtures';
import { useDemo } from '@/lib/demoStore';
import clsx from 'clsx';

const MonacoEditor = dynamic(() => import('@monaco-editor/react'), {
  ssr: false,
  loading: () => (
    <div className="flex-1 flex items-center justify-center bg-surface animate-pulse">
      <span className="text-[12px] text-muted font-mono">loading editor…</span>
    </div>
  ),
});

const FILES = [
  { name: 'cinematic_timeline.js', lang: 'javascript', content: TEMPLATE_CODE, badge: 'T1' },
  {
    name: 'chain.ts',
    lang: 'typescript',
    badge: 'gen',
    content: `// chain.ts — generated by ClassForge pipeline
// Source: photosynthesis_deck · cinematic_timeline template

import { LessonSpec } from './types';
import { CinematicTimeline } from './templates/cinematic_timeline';

export async function buildLesson(spec: LessonSpec): Promise<void> {
  const container = document.getElementById('app')!;
  const renderer = new CinematicTimeline(spec, container);

  // Phase sync via Firestore
  const db = getFirestore();
  const sessionRef = doc(db, 'sessions', spec.lessonId);

  onSnapshot(sessionRef, (snap) => {
    const data = snap.data();
    if (data?.currentPhase !== renderer.currentPhaseIndex) {
      renderer.goToPhase(data.currentPhase);
    }
    if (data?.paused) {
      renderer.pause();
    }
  });
}`,
  },
  {
    name: 'types.ts',
    lang: 'typescript',
    badge: 'shared',
    content: `// Shared type definitions — generated from spec schema

export interface LessonSpec {
  lessonId: string;
  title: string;
  subject: string;
  gradeLevel: number;
  template: TemplateId;
  phases: Phase[];
  safetyReport?: SafetyReport;
}

export type TemplateId =
  | 'cinematic_timeline'
  | 'scale_journey'
  | 'parameter_sandbox';

export interface Phase {
  phaseId: string;
  beatTitle: string;
  learningObjective: string;
  narration: Narration;
  scene: Scene;
  interaction: Interaction;
}`,
  },
];

export default function CodeTab() {
  const { state } = useDemo();
  const [activeFile, setActiveFile] = useState(FILES[0].name);
  const isBuilt = state.demoPhase === 'built' || state.demoPhase === 'ready';

  const currentFile = FILES.find(f => f.name === activeFile) ?? FILES[0];

  return (
    <div className="flex h-full">
      {/* File tree */}
      <div className="w-44 flex-shrink-0 border-r border-surface bg-surface-1 overflow-y-auto py-2">
        <div className="flex items-center gap-1 px-3 py-1 text-[11px] text-muted uppercase tracking-wider mb-1">
          <Folder className="w-3 h-3" />
          <span>src</span>
        </div>
        {FILES.map(file => (
          <button
            key={file.name}
            onClick={() => setActiveFile(file.name)}
            className={clsx(
              'w-full flex items-center gap-2 px-4 py-1.5 text-left transition-colors',
              activeFile === file.name
                ? 'bg-surface-3 text-white'
                : 'text-subtle hover:text-slate-300 hover:bg-surface-2'
            )}
          >
            <File className="w-3 h-3 flex-shrink-0" />
            <span className="text-[12px] truncate flex-1">{file.name}</span>
            {file.badge && (
              <span className={clsx(
                'text-[9px] px-1.5 py-0.5 rounded font-medium flex-shrink-0',
                file.badge === 'gen'
                  ? 'bg-brand/20 text-brand'
                  : file.badge === 'T1'
                  ? 'bg-teal-500/20 text-teal-400'
                  : 'bg-surface-3 text-muted'
              )}>
                {file.badge}
              </span>
            )}
          </button>
        ))}

        {!isBuilt && (
          <div className="px-3 py-4 mt-2 border-t border-surface">
            <p className="text-[11px] text-muted text-center">Files generated after Rebuild</p>
          </div>
        )}
      </div>

      {/* Editor */}
      <div className="flex-1 flex flex-col overflow-hidden">
        {/* Tab bar */}
        <div className="flex items-center border-b border-surface bg-surface-1 flex-shrink-0 px-2 py-1 gap-1">
          <div className="flex items-center gap-0.5 text-[12px] text-muted">
            <File className="w-3 h-3 text-brand" />
            <span className="text-slate-300 ml-1">{currentFile.name}</span>
            {currentFile.badge === 'gen' && (
              <span className="ml-1.5 text-[10px] bg-brand/20 text-brand px-1.5 py-0.5 rounded">generated</span>
            )}
          </div>
        </div>

        <MonacoEditor
          key={activeFile}
          height="100%"
          language={currentFile.lang}
          value={currentFile.content}
          theme="vs-dark"
          options={{
            readOnly: true,
            fontSize: 12,
            fontFamily: '"JetBrains Mono", monospace',
            fontLigatures: true,
            minimap: { enabled: false },
            scrollBeyondLastLine: false,
            padding: { top: 12 },
            lineNumbers: 'on',
            scrollbar: { verticalScrollbarSize: 5 },
          }}
        />
      </div>
    </div>
  );
}
